version: '3.8'

services:
  chihuahua-odb:
    image: container-registry.oracle.com/database/free:latest
    container_name: chihuahua-odb
    network_mode: "apples-network"
    ports:
      - "127.0.0.1:1521:1521"
    env_file:
      - .env
    restart: always

  juarez-odb:
    image: container-registry.oracle.com/database/free:latest
    container_name: juarez-odb
    network_mode: "apples-network"
    ports:
      - "127.0.0.1:1522:1521"
    env_file:
      - .env
    restart: always

  cuauhtemoc-odb:
    image: container-registry.oracle.com/database/free:latest
    container_name: cuauhtemoc-odb
    network_mode: "apples-network"
    ports:
      - "127.0.0.1:1523:1521"
    env_file:
      - .env
    restart: always
