drop table if exists apple_orchards;
CREATE TABLE apple_orchards (
    orchard_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    orchard_name VARCHAR2(255) NOT NULL,
    location VARCHAR2(255) NOT NULL,
    server VARCHAR2(255) NOT NULL CHECK (server IN ('chihuahua', 'juarez', 'cuauhtemoc'))
);

drop table if exists apple_orchard_sales;
CREATE TABLE apple_orchard_sales (
    sale_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    orchard_id NUMBER NOT NULL,
    sale_date DATE NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    quantity_sold NUMBER NOT NULL,
    CONSTRAINT fk_orchard FOREIGN KEY (orchard_id) REFERENCES apple_orchards(orchard_id)
);
